import { test, expect, CONV, HUMAN } from './fixtures'
for (const [id, human] of [[CONV, false], [HUMAN, true]] as const) {
  test(`conversation transcript, resolution and reopen (human=${human})`, async ({ page, login }) => {
    await login()
    await page.getByRole('navigation').getByRole('link', { name: 'Conversations' }).click()
    await expect(page.getByRole('link', { name: 'View conversation', exact: true })).toHaveCount(3)
    await expect(page.getByRole('button', { name: 'Previous', exact: true })).toBeDisabled()
    await expect(page.getByRole('button', { name: 'Next', exact: true })).toBeDisabled()
    await page.locator(`a[href="/app/conversations/${id}"]`).click()
    const transcript = page.getByRole('region', { name: 'Conversation transcript' })
    await expect(transcript.getByRole('heading', { name: 'Customer', exact: true })).toBeVisible()
    await expect(transcript.getByRole('heading', { name: 'SupportPilot AI', exact: true })).toBeVisible()
    await expect(transcript).toContainText('Shipping Policy')
    await expect(transcript).toContainText('Customer feedback: Helpful')
    await page.getByRole('button', { name: 'Resolve conversation', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Resolve conversation' })).toBeVisible()
    await page.getByRole('button', { name: 'Confirm resolve conversation' }).click()
    await expect(page.getByRole('button', { name: 'Reopen conversation', exact: true })).toBeVisible()
    await expect(page.getByText(/^resolved$/i)).toBeVisible()
    await page.getByRole('button', { name: 'Reopen conversation', exact: true }).click()
    if (human) await expect(page.getByRole('dialog')).toContainText('AI replies will remain paused')
    await page.getByRole('button', { name: 'Confirm reopen conversation' }).click()
    await expect(page.getByRole('button', { name: 'Resolve conversation', exact: true })).toBeVisible()
    await expect(page.getByText(human ? /^human requested$/i : /^open$/i).first()).toBeVisible()
  })
}
test.describe('stale mutation', () => {
  test.use({ scenario: 'conflict', expectedStatuses: [409] })
  test('409 exposes safe copy and refresh, never gateway payload', async ({ page, login }) => {
    await login()
    await page.goto(`/app/conversations/${CONV}`)
    await page.getByRole('button', { name: 'Resolve conversation', exact: true }).click()
    await page.getByRole('button', { name: 'Confirm resolve conversation' }).click()
    await expect(page.getByRole('alert')).toContainText(/changed|conflict|Refresh/i)
    await expect(page.locator('body')).not.toContainText('synthetic private SQL')
    await page.getByRole('button', { name: 'Refresh record', exact: true }).click()
    await expect(page.getByText(/^unresolved$/i)).toBeVisible()
  })
})
