import { test, expect, PUBLIC, API, send, finish } from './fixtures'

test('hosted real SSE, trusted citations, feedback and history reload', async ({ page, release }) => {
  await page.goto(`/chat/${PUBLIC}`)
  const stream = page.waitForResponse(response => response.url().endsWith('/turns/stream'))
  await send(page)
  expect((await stream).headers()['content-type']).toContain('text/event-stream')
  await finish(page, release)
  await expect(page.getByRole('listitem').filter({ hasText: /^1\. Shipping Policy — page 2$/ })).toBeVisible()
  await expect(page.getByText(/Page 2/i)).toBeVisible()
  await page.getByRole('button', { name: 'Mark this answer as helpful', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Mark this answer as helpful', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Mark this answer as not helpful', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Mark this answer as not helpful', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(page.getByText('Orders ship within two days.', { exact: true })).toBeVisible()
  await expect(page.getByText('When do orders ship?', { exact: true })).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Mark this answer as not helpful', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test.describe('failed partial', () => {
  test.use({ scenario: 'retry' })
  test('partial removed, same ID retried, one persisted customer turn', async ({ page, request, release }) => {
    await page.goto(`/chat/${PUBLIC}`)
    await send(page)
    await expect(page.getByLabel('Assistant response in progress')).toContainText('Orders ')
    await release(0)
    await expect(page.getByRole('button', { name: 'Retry', exact: true })).toBeVisible()
    await expect(page.getByLabel('Assistant response in progress')).toHaveCount(0)
    await expect(page.getByText('Orders ', { exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Retry', exact: true }).click()
    await release(1)
    await expect(page.getByText('Orders ship within two days.', { exact: true })).toBeVisible()
    const state = await (await request.get(`${API}/_e2e/state`)).json()
    expect(state.attempts).toHaveLength(2)
    expect(new Set(state.attempts).size).toBe(1)
    expect(state.messages).toBe(2)
    await expect(page.getByText('When do orders ship?', { exact: true })).toHaveCount(1)
  })
})

test.describe('throttled turn', () => {
  test.use({ scenario: 'throttle', expectedStatuses: [429] })
  test('429 manual cooldown retains ID without automatic retries', async ({ page, request, release }) => {
    await page.clock.install()
    await page.goto(`/chat/${PUBLIC}`)
    await send(page)
    const retry = page.getByRole('button', { name: /Retry in/ })
    await expect(retry).toBeDisabled()
    await expect(page.getByText('Too many requests. Please try again shortly.', { exact: true })).toBeVisible()
    await expect(page.locator('body')).not.toContainText(/PT429|PostgREST|SQL|token_hash/)
    expect((await (await request.get(`${API}/_e2e/state`)).json()).attempts).toHaveLength(1)
    await page.clock.runFor(2100)
    await expect(page.getByRole('button', { name: 'Retry', exact: true })).toBeEnabled()
    expect((await (await request.get(`${API}/_e2e/state`)).json()).attempts).toHaveLength(1)
    await page.getByRole('button', { name: 'Retry', exact: true }).click()
    await finish(page, release)
    const state = await (await request.get(`${API}/_e2e/state`)).json()
    expect(new Set(state.attempts).size).toBe(1)
    await expect(page.getByText('When do orders ship?', { exact: true })).toHaveCount(1)
  })
})

test.describe('feedback rejection', () => {
  test.use({ scenario: 'feedback_fail', expectedStatuses: [429] })
  test('rejected feedback never claims success', async ({ page, release }) => {
    await page.goto(`/chat/${PUBLIC}`)
    await send(page)
    await finish(page, release)
    const helpful = page.getByRole('button', { name: 'Mark this answer as helpful', exact: true })
    await helpful.click()
    await expect(page.getByText(/couldn't save that feedback/)).toBeVisible()
    await expect(helpful).toHaveAttribute('aria-pressed', 'false')
  })
})

test.describe('human handoff', () => {
  test.use({ scenario: 'insufficient' })
  test('insufficient evidence, confirmed human request and paused AI', async ({ page }) => {
    await page.goto(`/chat/${PUBLIC}`)
    await send(page)
    await expect(page.getByRole('button', { name: 'Mark this answer as helpful', exact: true })).toBeVisible()
    await expect(page.getByText("I don't have enough information in the available knowledge base to answer that reliably.", { exact: true })).toBeVisible()
    await expect(page.getByRole('listitem').filter({ hasText: 'Shipping Policy' })).toHaveCount(0)
    await expect(page.getByLabel('Assistant response in progress')).toHaveCount(0)
    await page.getByRole('button', { name: 'Request a human', exact: true }).first().click()
    await page.getByRole('button', { name: 'Confirm', exact: true }).click()
    await expect(page.getByText('A human support request has been recorded.')).toBeVisible()
    await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toBeDisabled()
    await expect(page.getByRole('button', { name: 'Request a human', exact: true })).toHaveCount(0)
    await page.reload()
    await expect(page.getByText('AI messaging is paused for this conversation.')).toBeVisible()
  })
})

test('closed conversation history is readable and sending disabled', async ({ page, request, release }) => {
  await page.goto(`/chat/${PUBLIC}`)
  await send(page)
  await finish(page, release)
  expect((await request.post(`${API}/_e2e/close`)).ok()).toBeTruthy()
  await page.reload()
  await expect(page.getByText('Orders ship within two days.', { exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeDisabled()
  await expect(page.getByRole('status')).toContainText('This conversation is closed.')
  await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toHaveAttribute('placeholder', 'This conversation is not accepting new messages.')
})

test.describe('safe public error', () => {
  test.use({ scenario: 'internal', expectedStatuses: [502] })
  test('gateway internal-looking payload never reaches browser copy', async ({ page }) => {
    await page.goto(`/chat/${PUBLIC}`)
    await send(page)
    await expect(page.getByRole('button', { name: 'Retry', exact: true })).toBeVisible()
    await expect(page.locator('body')).not.toContainText(/SELECT|XX000|secret-looking|stack trace/)
    await expect(page.getByLabel('Assistant response in progress')).toHaveCount(0)
  })
})
