import { test, expect, ESC, API } from './fixtures'
test.use({ scenario: 'pending' })
test('escalation pending controls and start/resolve/reopen/close', async ({ page, login, request, release }) => {
  await login()
  await page.getByRole('navigation').getByRole('link', { name: 'Escalations' }).click()
  await page.locator(`a[href="/app/escalations/${ESC}"]`).click()
  await page.getByRole('button', { name: 'Start work', exact: true }).click()
  await expect.poll(async () => (await (await request.get(`${API}/_e2e/state`)).json()).delay_started).toBe(true)
  await expect(page.getByRole('button', { name: 'Start work', exact: true })).toBeDisabled()
  await expect(page.getByText(/^open$/i)).toBeVisible()
  await release(2)
  await expect(page.getByText(/^in progress$/i)).toBeVisible()
  await page.getByRole('button', { name: 'Resolve', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm resolve', exact: true }).click()
  await expect(page.getByText(/^resolved$/i)).toBeVisible()
  await page.getByRole('button', { name: 'Reopen', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Start work', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm close', exact: true }).click()
  await expect(page.getByText(/^closed$/i)).toBeVisible()
})
