import { test, expect, PUBLIC, ORIGIN, API } from './fixtures'
test.use({ scenario: 'pending' })
test('widget snippet, copy and server-confirmed enable/disable', async ({ page, login, request, release }) => {
  await login()
  await page.getByRole('navigation').getByRole('link', { name: 'Widget', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Support widget' })).toBeVisible()
  await expect(page.getByLabel('Embed code')).toHaveValue(new RegExp(`${ORIGIN}/supportpilot-widget.js`))
  await expect(page.getByLabel('Embed code')).toHaveValue(new RegExp(PUBLIC))
  await page.getByRole('button', { name: 'Copy embed code' }).click()
  await expect(page.getByRole('status').filter({ hasText: /copied|Copy is unavailable/ })).toBeVisible()
  await page.getByRole('button', { name: 'Disable widget', exact: true }).click()
  await expect.poll(async () => (await (await request.get(`${API}/_e2e/state`)).json()).delay_started).toBe(true)
  await expect(page.getByRole('button', { name: 'Saving…' })).toBeDisabled()
  await expect(page.getByText('Enabled', { exact: true })).toBeVisible()
  await release(2)
  await expect(page.getByText('Disabled', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Enable widget', exact: true }).click()
  await expect(page.getByText('Enabled', { exact: true })).toBeVisible()
})
